# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	ENV["LC_ALL"] = "de_DE.UTF-8"
	config.vm.box = "javiercanadillas/sw4iot"
	config.vm.provider "virtualbox" do |vb|
		vb.gui = true
		vb.customize ["modifyvm", :id, "--vram", "100"]
		vb.memory = "2048"
		vb.linked_clone = true
	end

	config.vm.provision "shell", inline: <<-SHELL
		sudo usermod -a -G sudo vagrant
		sudo apt-get update
		sudo apt-get -y remove docker docker.io containerd runc
		sudo apt-get install -y \
			ca-certificates \
			curl \
			gnupg \
			lsb-release
			curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
			echo \
				"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
				$(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
		sudo apt-get update
		sudo apt-get install -y docker docker-ce docker-ce-cli containerd.io
		sudo apt-get install git
		sudo apt-get install -y default-jdk
		sudo snap install --classic eclipse
		sudo shutdown -r now
	SHELL
end
