/* Generated By:JavaCC: Do not edit this line. While0Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface While0Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHILE = 5;
  /** RegularExpression Id. */
  int DO = 6;
  /** RegularExpression Id. */
  int END = 7;
  /** RegularExpression Id. */
  int NEQ = 8;
  /** RegularExpression Id. */
  int VARIABLE = 9;
  /** RegularExpression Id. */
  int ALPHA_ = 10;
  /** RegularExpression Id. */
  int VALUE_OPS = 11;
  /** RegularExpression Id. */
  int VARIABLE_INC = 12;
  /** RegularExpression Id. */
  int VARIABLE_ZERO = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"while\"",
    "\"do\"",
    "\"end\"",
    "\"!=\"",
    "<VARIABLE>",
    "<ALPHA_>",
    "<VALUE_OPS>",
    "<VARIABLE_INC>",
    "<VARIABLE_ZERO>",
    "\"NAME=(in\"",
    "\"; out\"",
    "\");\"",
    "\"var(\"",
    "\",\"",
  };

}
