/* Generated By:JavaCC: Do not edit this line. While0Constants.java */
package fh.aachen.praktikum1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface While0Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IN = 5;
  /** RegularExpression Id. */
  int OUT = 6;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int BEGIN = 8;
  /** RegularExpression Id. */
  int DO = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int LOC = 11;
  /** RegularExpression Id. */
  int NEQ = 12;
  /** RegularExpression Id. */
  int EQ = 13;
  /** RegularExpression Id. */
  int SEMICOLON = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int OPENING_BRACKET = 16;
  /** RegularExpression Id. */
  int CLOSING_BRACKET = 17;
  /** RegularExpression Id. */
  int VARIABLE = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"in\"",
    "\"out\"",
    "\"while\"",
    "\"begin\"",
    "\"do\"",
    "\"end\"",
    "\"var\"",
    "\"!=\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<VARIABLE>",
    "\"0\"",
    "\"+\"",
    "\"1\"",
  };

}
