name: graphlib-workflow
on: [ push ]
jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -f "./malgo/graphlib/pom.xml" --batch-mode --update-snapshots package